### ISSUE TITLE
max_combo seems to not get updated

### ISSUE THREAD

**Issue by kanaarima** [osuTitanic/deck#33]

**Comment by Lekuruu** [comment]
Pretty stupid mistake on my end 😅 

```python
max_combo_score = score.session.query(DBScore) \
    .filter(DBScore.user_id == score.user.id) \
    .order_by(DBScore.max_combo.desc()) \
    .first()

if max_combo_score:
    if score.max_combo > max_combo_score.max_combo:
        stats.max_combo = score.max_combo
```

tl;dr, when querying for the `max_combo_score`, it will return the score with the highest combo, which can also be the current score that was submitted already. That means that the comparison for `score.max_combo > max_combo_score.max_combo` will always result in being `False`.

Easier would be to just do this:

```python
if score.max_combo > stats.max_combo:
    stats.max_combo = score.max_combo
```

I am not really sure why I did it this way...

**Comment by kanaarima** [comment]
that was pretty easy to overlook tbh

**Comment by Lekuruu** [comment]
will be included in next pr
